version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - MONGODB_URI="mongodb://kasthaneda:AYloln6hji7uoUbl@ac-gdnwry9-shard-00-00.hcukmyd.mongodb.net:27017,ac-gdnwry9-shard-00-01.hcukmyd.mongodb.net:27017,ac-gdnwry9-shard-00-02.hcukmyd.mongodb.net:27017/?ssl=true&replicaSet=atlas-h1z25r-shard-0&authSource=admin&retryWrites=true&w=majority"
      - MONGO_PORT=27017
    networks:
      - app-network
  mongo:
    image: mongo:latest
    ports:
      - '27017'
    volumes:
      - mongodata:/data/db
    networks:
      - app-network
volumes:
  mongodata:
networks:
  app-network:
    driver: bridge 
